INSERT INTO public_holidays (id, date, name, region) VALUES
                                                         (gen_random_uuid(), '2025-01-01', 'New Year''s Day',           'ENGLAND'),
                                                         (gen_random_uuid(), '2025-04-18', 'Good Friday',               'ENGLAND'),
                                                         (gen_random_uuid(), '2025-04-21', 'Easter Monday',             'ENGLAND'),
                                                         (gen_random_uuid(), '2025-05-05', 'Early May Bank Holiday',    'ENGLAND'),
                                                         (gen_random_uuid(), '2025-05-26', 'Spring Bank Holiday',       'ENGLAND'),
                                                         (gen_random_uuid(), '2025-08-25', 'Summer Bank Holiday',       'ENGLAND'),
                                                         (gen_random_uuid(), '2025-12-25', 'Christmas Day',             'ENGLAND'),
                                                         (gen_random_uuid(), '2025-12-26', 'Boxing Day',                'ENGLAND'),
                                                         (gen_random_uuid(), '2026-01-01', 'New Year''s Day',           'ENGLAND'),
                                                         (gen_random_uuid(), '2026-04-03', 'Good Friday',               'ENGLAND'),
                                                         (gen_random_uuid(), '2026-04-06', 'Easter Monday',             'ENGLAND'),
                                                         (gen_random_uuid(), '2026-05-04', 'Early May Bank Holiday',    'ENGLAND'),
                                                         (gen_random_uuid(), '2026-05-25', 'Spring Bank Holiday',       'ENGLAND'),
                                                         (gen_random_uuid(), '2026-08-31', 'Summer Bank Holiday',       'ENGLAND'),
                                                         (gen_random_uuid(), '2026-12-25', 'Christmas Day',             'ENGLAND'),
                                                         (gen_random_uuid(), '2026-12-28', 'Boxing Day (substitute)',   'ENGLAND');